backend:
  name: github
  repo: yuko-mlg/surya-pangan-web # Repository GitHub Anda
  branch: main 
  base_url: https://surya-pangan-web.vercel.app # Ganti dengan domain Vercel Anda nanti
  site_url: https://surya-pangan-web.vercel.app
  auth_endpoint: api/auth
publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "assets/images"

collections:
  - name: "news_id"
    label: "Berita (ID)"
    files:
      - name: "berita_data"
        label: "Konten Berita Indonesia"
        file: "public/data/news_id.json"
        description: "Daftar berita dalam Bahasa Indonesia"
        fields:
          - label: "Daftar Berita"
            name: "news"
            widget: "list"
            fields:
              - {label: "ID (Unik)", name: "id", widget: "number", value_type: "int"}
              - {label: "Tanggal Mulai", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Tanggal Kadaluwarsa (Opsional)", name: "expiry_date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false}
              - {label: "Gambar", name: "image", widget: "image"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
              - {label: "Judul News (ID)", name: "title", widget: "string"}
              - {label: "Ringkasan News (ID)", name: "summary", widget: "text"}

  - name: "news_en"
    label: "News (EN)"
    files:
      - name: "news_data_en"
        label: "English News Content"
        file: "public/data/news_en.json"
        description: "List of news in English"
        fields:
          - label: "News List"
            name: "news"
            widget: "list"
            fields:
              - {label: "ID (Unique)", name: "id", widget: "number", value_type: "int"}
              - {label: "Start Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Expiry Date (Optional)", name: "expiry_date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Link", name: "link", widget: "string", default: "#"}
              - {label: "Title (EN)", name: "title", widget: "string"}
              - {label: "Summary (EN)", name: "summary", widget: "text"}
